### ISSUE TITLE
Leaked DB Connection Error!

### ISSUE THREAD

**Issue by congaterori** [alpkeskin/mosint#11]
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000231D8A86F70>
Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Leaked DB Connection Error!

**Comment by w1th0ut** [comment]
Yes, https://scylla.sh this website down

**Comment by alpkeskin** [comment]
Hi, current domain address : https://scylla.so but they have not yet opened the API to public. I'll update **mosint** when they go public. 🚀
