### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 077uyp** [alpkeskin/mosint#13]
Traceback (most recent call last):
  File "/home/user/mosint/modules/SocialScan.py", line 1, in <module>
    from socialscan.util import Platforms, sync_execute_queries
  File "/home/user/.local/lib/python3.9/site-packages/socialscan/util.py", line 9, in <module>
    import aiohttp
  File "/usr/lib/python3/dist-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/usr/lib/python3/dist-packages/aiohttp/client.py", line 35, in <module>
    from . import hdrs, http, payload
  File "/usr/lib/python3/dist-packages/aiohttp/http.py", line 7, in <module>
    from .http_parser import (
  File "/usr/lib/python3/dist-packages/aiohttp/http_parser.py", line 15, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "/usr/lib/python3/dist-packages/aiohttp/helpers.py", line 667, in <module>
    class CeilTimeout(async_timeout.timeout):
TypeError: function() argument 'code' must be code, not str

**Comment by opticoax747** [comment]
Same here, did u find a solution?

**Comment by alpkeskin** [comment]
What version of python are you using?

**Comment by opticoax747** [comment]
/mosint$ python3 --version
Python 3.7.3
***@***.***:~/mosint$

**Comment by opticoax747** [comment]
> 

both /mosint$ python3 --version
Python 3.7.3

and Python 2.7 are installed

can I force go to run with Python3?

**Comment by alpkeskin** [comment]
I think there is a problem with your python version or the libraries you are using. The simple way is you can update the version of `python3` and reinstall the `aiohttp` library.

**Comment by calganaygun** [comment]
Hey, @opticoax747 I think this bug is related to [socialscan package](https://github.com/iojw/socialscan). Can you share your OS and aiohttp version?

To find the aiohttp version you're using:
````bash
python3 -m pip freeze | grep aiohttp
