### ISSUE TITLE
Panic 'invalid character '<' looking for beginning of value'

### ISSUE THREAD

**Issue by d0znpp** [alpkeskin/mosint#25]
Here is the thing:

```   Now: Saturday, 11 Jun 2022

mosinting  28% |██████████████████████████                                                                   | (28/100, 8 it/s) [3s:8s]panic: invalid character '<' looking for beginning of value

goroutine 1 [running]:
main/modules.doRequest({0xc0000263c0, 0x49}, {0xa64ddc, 0x6})
	/home/x/tools/mosint/modules/ThreatCrowd.go:28 +0x670
main/modules.RelatedEmails({0x7ffd138353e8?, 0x12?})
	/home/x/tools/mosint/modules/ThreatCrowd.go:56 +0x65
main.main()
	/home/x/tools/mosint/main.go:261 +0xbcd
exit status 2
```

**Comment by calganaygun** [comment]
It is about the ThreatCrowd API. They are returning 504 when you try to get any report. There are no status code checks in the code.

**Comment by calganaygun** [comment]
Can you check if this fixes your problem? @d0znpp

**Comment by d0znpp** [comment]
yes, now it's OK!

**Comment by nikolarovcanin** [comment]
I have same issue, can some explain me how to fix the problem
