### ISSUE TITLE
PDF Check for Related Emails

### ISSUE THREAD

**Issue by phanthuthao** [alpkeskin/mosint#6]
Traceback (most recent call last):
  File "/home/Monkey/soft/mosint/mosint.py", line 115, in <module>
    main()
  File "/home/Monkey/soft/mosint/mosint.py", line 34, in main
    checkPDF = (i['PDF Check for Related Emails'])
KeyError: 'PDF Check for Related Emails'

**Comment by alpkeskin** [comment]
You should download the new config.json
