### ISSUE TITLE
panic google block

### ISSUE THREAD

**Issue by 0xTides** [alpkeskin/mosint#72]
I'm getting the following error when trying to run the script.

```
panic: google block

goroutine 6 [running]:
github.com/alpkeskin/mosint/cmd/controllers.Googling({0x7ffcf51ced54?, 0x1?})
        /root/mosint/cmd/controllers/googling.go:18 +0x1d8
github.com/alpkeskin/mosint/cmd.Do.func1()
        /root/mosint/cmd/handler.go:49 +0x32
github.com/gammazero/workerpool.worker(0x0?, 0x0?, 0x0?)
        /root/go/pkg/mod/github.com/gammazero/workerpool@v1.1.3/workerpool.go:237 +0x2a
created by github.com/gammazero/workerpool.(*WorkerPool).dispatch
        /root/go/pkg/mod/github.com/gammazero/workerpool@v1.1.3/workerpool.go:197 +0x2b8
exit status 2
```

Any help would be appreciated.

**Comment by alpkeskin** [comment]
Bugs have been fixed in the new version (v3.0.0). Ensure the config file is configured correctly for **Mosint** to work properly.
